apiVersion: apps/v1
kind: Deployment
metadata: 
  name: storage-node
spec:
  replicas: 24
  selector:
    matchLabels:
      app: storage-node
  template: 
    metadata:
      labels: 
        app: storage-node
    spec: 
      containers:
        - name: storage-node
          image: therealnestor/ds:storage-node
          resources:
            requests: 
              memory: "100Mi"
            limits:
              memory: "350Mi"
          imagePullPolicy: Always
          ports: 
            - containerPort: 5000

          