FROM python:3.9-slim

WORKDIR /app

COPY src/ /app/
COPY requirements.txt /app/

RUN pip install -r requirements.txt

# Expose port for REST API
EXPOSE 5001

# Command to run the storage node API
CMD ["python", "api/node_api.py"]