from node_selection import MIN_COPY_SETS_SELECTION, RANDOM_SELECTION, BUDDY_SELECTION

# NO_NODES = 4 # Hardcoded into yaml file.
NO_REPLICAS = 3
NO_FRAGMENTS = 4
NODE_SELECTION_STRATEGY = RANDOM_SELECTION
NODES_TO_KILL = 10
