apiVersion: v1
kind: Service
metadata:
  name: lead-node-service
spec:
  selector:
    app: lead-node
  ports:
    - port: 4000
      targetPort: 4000
  type: NodePort  # accessible from outside the cluster